### ISSUE TITLE
SVGRender info

### ISSUE THREAD

**Issue by omarirfa** [ximinng/PyTorch-SVGRender#1]
Hi, 

I loved reading your diffsketcher paper and recently saw on the diffsketcher github repo that you are releasing a Pytorch-SVGRender which is SOTA in differentiable rendering 👀👀! 

I was wondering if there is somewhere I can read more about it? I tried checking the docs and the github-pages website but think those are just placeholders atm. 

Have a great day!

**Comment by ximinng** [comment]
Hello omarirfa,

Apologies for the delayed response. We appreciate your interest in our work.

We developed PyTorch-SVGRender as a repository for people to rapidly create vector graphics. We are committed to improving it further.

In the meantime, our paper, "SVGDreamer: Text Guided SVG Generation with Diffusion Model" has been uploaded on arxiv. We plan to publish the complete code once the paper is accepted.

Parts of the SVGDreamer code for VPSD will be made available in advance through PyTorch-SVGRender.

Best regards,
Ximing

**Comment by omarirfa** [comment]
Hi Ximing!

Thank you for your reply! I read the ppr you referenced, it was a very interesting read (and quite surprising you and the team are publishing even near new year!) and I could see how you and everyone else improved upon existing techniques and even used new ones! 

Excited to see VPSD and hoping SIVE is also there!


Just one question:

1. Will there also be a paper for PyTorch-SVGRender specifically or will it only be a repo?

Best Regards,
Omar

**Comment by ximinng** [comment]
Hello omarirfa,

I hope PyTorch-SVGRender can serve as a reusable repository for the community. I will write documentation for it and  a technical report.

If you come across any interesting techniques that can enhance the current SVG rendering, I would be glad to integrate them into PyTorch-SVGRender.

Currently, this repository is incomplete, and my team and I will continue to work on it in the coming year.

Lastly, I wish you a happy New Year.

Best regards,
Ximing

**Comment by omarirfa** [comment]
Hi Ximing!

Sounds good and will keep an eye out for papers! 

Best of luck to you and your team and happy new year to you as well!

Best Regards,
Omar
