### ISSUE TITLE
svgdreamer error

### ISSUE THREAD

**Issue by omarirfa** [ximinng/PyTorch-SVGRender#12]
Hi Ximing and team!

After installing pytorch svg-render on ubuntu 22.04 using the install.sh script provided, I get this error while running the command in conda:

Command:
```sh
python svg_render.py x=svgdreamer "prompt='A colorful German shepherd in vector art. tending on artstation.'" save_step=30 x.guidance.n_particle=6 x.guidance.vsd_n_particle=4 x.guidance.phi_n_particle=2 result_path='./svgdreamer/GermanShepherd'
```
Error:
![image](https://github.com/ximinng/PyTorch-SVGRender/assets/61637151/4f73e88f-1e32-4df0-82c6-58ca4771adec)

An error above this line says hugging face cannot find the model in the disk cache. 

Hugging face error:
![image](https://github.com/ximinng/PyTorch-SVGRender/assets/61637151/26f17327-f678-49bb-9bb0-6f03f1d34669)

I am wondering if we are supposed to install stable diffusion from [here](https://huggingface.co/stabilityai/stable-diffusion-2-1/tree/main) and then run it? given I think in the __init__.py file the local_files_only parameter is set to True. So it will only look for files locally instead of getting them from online.

Best Regards,
Omar

**Comment by ximinng** [comment]
hello omarirfa,

Your understanding is correct. Download the model and run the script via `diffuser.download=True`

```bash
python svg_render.py x=svgdreamer "prompt='A colorful German shepherd in vector art. tending on artstation.'" save_step=30 x.guidance.n_particle=6 x.guidance.vsd_n_particle=4 x.guidance.phi_n_particle=2 result_path='./svgdreamer/GermanShepherd' diffuser.download=True
```

Best Regards,
ximing

**Comment by omarirfa** [comment]
Hi Ximing,

Thanks for your reply. I will test it out!

Best Regards,
Omar
