### ISSUE TITLE
'fairscale=0.4.13' should be 'fairscale==0.4.13'

### ISSUE THREAD

**Issue by wendashi** [ximinng/PyTorch-SVGRender#15]
(svgrender) username :~/path/to/svgrender$ pip install numpy scipy scikit-fmm einops timm fairscale=0.4.13
ERROR: Invalid requirement: 'fairscale=0.4.13'
Hint: = is not a valid operator. Did you mean == ?

https://pytorch-svgrender.readthedocs.io/en/latest/install.html

**Comment by ximinng** [comment]
Yes, it's a typo.  It has been corrected.
