### ISSUE TITLE
Anther typo (StyleCLIPDraw might be CLIPFont)

### ISSUE THREAD

**Issue by wendashi** [ximinng/PyTorch-SVGRender#16]
Link: https://pytorch-svgrender.readthedocs.io/en/latest/clipfont.html

![image](https://github.com/ximinng/PyTorch-SVGRender/assets/141135497/974bd4b4-a260-4bd0-8d81-f7ef6147e811)

**Comment by ximinng** [comment]
Dear wendashi,

I wanted to thank you for catching my typo. Your attention to detail is greatly appreciated!

Sincerely,
ximing
