### ISSUE TITLE
How to avoid redundant vector lines when using DiffVG?

### ISSUE THREAD

**Issue by xuanlongORZ** [ximinng/PyTorch-SVGRender#19]
Hi ! Thanks for the great work !
I'm trying to vetorize my lineart using DiffSVG with default settings, but I found that in the final .svg, there are many initial vector lines that are useless (in the .png final output, they are strangely not very visible). I wonder if this is due to the wrong estimation of the number of the initialization vector lines (I'm pretty new to this area, forgive me if this is a stupid question :D ). Is this kind of problem unavoidable?

**Comment by ximinng** [comment]
Hello,
There are invisible paths (i.e low opacity) because you are using too many paths. Adjusting the `num_paths` hyperparameter will give better results.
best regards,
ximing
