### ISSUE TITLE
install.sh not working

### ISSUE THREAD

**Issue by shubhamgarg21** [ximinng/PyTorch-SVGRender#5]
Hi,
i am trying to setup local clone of this amazing repo, but it seems the below link has been deleted. 
https://disk.yandex.ru/d/kHJkc7bs7mKIVA

can you help with the alternate link?

**Comment by ximinng** [comment]
Hello shubhamgarg21,

For now you can just skip the model download and we'll fix the link as soon as possible.

best regards,
ximing

**Comment by ximinng** [comment]
We provide a new link in install.sh

```shell
cd lama
curl -O -L https://huggingface.co/xingxm/PyTorch-SVGRender-models/resolve/main/big-lama.zip
unzip big-lama.zip
```
