### ISSUE TITLE
Does it have an option to convert bitmap to vector ? 

### ISSUE THREAD

**Issue by YBMENACE** [ximinng/PyTorch-SVGRender#6]
Does it have an option to convert bitmap to vector ? 

Is it an AI model ? 

Like : https://vectorizer.ai/

**Comment by YBMENACE** [comment]
Also i get this erro -- Build files have been written to: /root/PyTorch-SVGRender/lama/diffvg/build/temp.linux-x86_64-cpython-310
[ 14%] Building NVCC (Device) object CMakeFiles/diffvg.dir/diffvg_generated_scene.cpp.o
[ 28%] Building NVCC (Device) object CMakeFiles/diffvg.dir/diffvg_generated_diffvg.cpp.o
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
CMake Error at diffvg_generated_diffvg.cpp.o.Release.cmake:280 (message):
  Error generating file
  /root/PyTorch-SVGRender/lama/diffvg/build/temp.linux-x86_64-cpython-310/CMakeFiles/diffvg.dir//./diffvg_generated_diffvg.cpp.o


gmake[2]: *** [CMakeFiles/diffvg.dir/build.make:77: CMakeFiles/diffvg.dir/diffvg_generated_diffvg.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:99: CMakeFiles/diffvg.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

**Comment by ximinng** [comment]
Sure, here are examples:

```
# 1. DiffVG: img-to-svg
python svg_render.py x=diffvg target='./data/fallingwater.png'
# change 'num_paths' and 'num_iter' for better results
python svg_render.py x=diffvg target='./data/fallingwater.png' x.num_paths=512 x.num_iter=2000

# 2. LIVE: img-to-svg
python svg_render.py x=live target='./data/simile.png'
# change 'num_paths' and 'schedule_each' for better results
python svg_render.py x=live target='./data/simile.png' x.num_paths=5 x.schedule_each=1

```
